-- MySQL Script generated by MySQL Workbench
-- Sun Jun 17 22:59:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ulov_domov
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ulov_domov
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ulov_domov` DEFAULT CHARACTER SET utf8 ;
USE `ulov_domov` ;

-- -----------------------------------------------------
-- Table `ulov_domov`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulov_domov`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `ulov_domov`.`user_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulov_domov`.`user_admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`id` ASC),
  INDEX `fk_user_admin_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_admin_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `ulov_domov`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ulov_domov`.`village`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulov_domov`.`village` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ulov_domov`.`right`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulov_domov`.`right` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ulov_domov`.`user_village_right`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulov_domov`.`user_village_right` (
  `user_admin_id` INT NOT NULL,
  `village_id` INT NOT NULL,
  `right_id` INT NOT NULL,
  INDEX `fk_user_village_right_user_admin1_idx` (`user_admin_id` ASC),
  INDEX `fk_user_village_right_village1_idx` (`village_id` ASC),
  INDEX `fk_user_village_right_right1_idx` (`right_id` ASC),
  CONSTRAINT `fk_user_village_right_user_admin1`
    FOREIGN KEY (`user_admin_id`)
    REFERENCES `ulov_domov`.`user_admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_village_right_village1`
    FOREIGN KEY (`village_id`)
    REFERENCES `ulov_domov`.`village` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_village_right_right1`
    FOREIGN KEY (`right_id`)
    REFERENCES `ulov_domov`.`right` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
